run-dist:
	./build/install/app/bin/app "/Users/svitkovskiy/Projects/java-project-71/app/src/test/resources/test1.yml" "/Users/svitkovskiy/Projects/java-project-71/app/src/test/resources/test2.yml" -f plain

.PHONY: build

build:
	gradle build